title: Step by step tutorial
baseurl: "/vefhonnun"
url: "https://1910003230.github.io"

collections:
  authors:
    output: true

defaults:
  - scope:
      path: "/vefhonnun"
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: "/vefhonnun"
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "/vefhonnun"
    values:
      layout: "default"